Update create_issue.yml

diff --git a/.github/workflows/create_issue.yml b/.github/workflows/create_issue.yml
--- a/.github/workflows/create_issue.yml
+++ b/.github/workflows/create_issue.yml
@@ -20,6 +20,14 @@ jobs:
 
           # Fetch delivery IDs within the last 24 hours
           API_RESPONSE=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries?since=$START_TIMESTAMP")
+          
+          # Check if the response is empty or not valid JSON
+          if ! jq -e . >/dev/null 2>&1 <<<"$API_RESPONSE"; then
+            echo "Invalid JSON response or empty response."
+            exit 1
+          fi
+          
+          # Extract the "id" field from the JSON
           DELIVERY_IDS=($(echo "$API_RESPONSE" | jq -r '.[].id'))
 
           if [ ${#DELIVERY_IDS[@]} -eq 0 ]; then
@@ -40,6 +48,12 @@ jobs:
           for DELIVERY_ID in "${DELIVERY_IDS[@]}"; do
             # Get the payload for the delivery ID
             PAYLOAD=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries/$DELIVERY_ID")
+
+            # Check if the response is empty or not valid JSON
+            if ! jq -e . >/dev/null 2>&1 <<<"$PAYLOAD"; then
+              echo "Invalid JSON response or empty response for Delivery ID $DELIVERY_ID."
+              continue  # Skip to the next Delivery ID if this one is not valid.
+            fi
 
             # Extract the "action" field from the payload
             ACTION=$(echo "$PAYLOAD" | jq -r '.action')
